project:
  type: website
  output-dir: docs

website:
  title: "Vrunda Tol"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: journal
      dark: solar
    css: styles.css
    toc: true

editor: visual

